# Generated by Django 3.1 on 2020-08-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200816_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='icone',
            field=models.CharField(choices=[('lni-laptop-phone', 'Notbook'), ('lni-layers', 'Layer'), ('lni-cog', 'Engrenagem'), ('lni-rocket', 'Foguete'), ('lni-leaf', 'Folha')], max_length=17, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-stats-up', 'grafico'), ('lni-layers', 'Design'), ('lni-cog', 'Engrenagem'), ('lni-users', 'Usuario'), ('lni-rocket', 'Foguete'), ('lni-mobile', 'Molibe')], max_length=15, verbose_name='Icone'),
        ),
    ]
